/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphou;

/**
 *
 * @author stephane
 */
public class Aide extends javax.swing.JDialog {

    /**
     * Creates new form Aide
     */
    public Aide(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Graph'ou :: Aide");
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLayeredPane1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("La première étape du travail consiste à :");
        jLabel2.setBounds(10, 10, 190, 20);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("- Choisir la nature du graphe et valider sous le boutton en dessus de la zone de sélection");
        jLabel3.setBounds(10, 30, 630, 14);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphou/2013-05-01_071946.png"))); // NOI18N
        jButton2.setBounds(20, 50, 200, 160);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("- Ou alors restaurer un graphe au cas ou vous avez eu à en sauvegarder un antérieurement.");
        jLabel4.setBounds(10, 220, 670, 14);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("pour faire une restauration, vous cliquez sur le boutton restaurer (en bas à droite)ou vous vous");
        jLabel5.setBounds(20, 230, 580, 20);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("rendez tout simplement dans le menu Graphe->Restaurer... une fenêtre de selection de fichier s'ouvre vous");
        jLabel6.setBounds(20, 250, 590, 10);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("permettant de naviguer dans vos disques pour rechercher votre fichier de graphe dynamique à l'extension (.kmk)");
        jLabel7.setBounds(20, 260, 650, 14);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Etape 1", jLayeredPane1);

        jLabel8.setText("Une fois que la nature du graphe est choisie ou que le graphe est restauré, vous pouvez à tout moment appliquer des");
        jLabel8.setBounds(10, 0, 680, 14);
        jLayeredPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setText("Modifications à ce dernier en y joutant des sommets et des arêtes.");
        jLabel9.setBounds(10, 10, 570, 20);
        jLayeredPane2.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("1 - Ajout d'un Arc");
        jLabel10.setBounds(10, 120, 120, 14);
        jLayeredPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setText("Ajouter un sommet est très simple et celà se fait comme suit : ");
        jLabel11.setBounds(10, 50, 570, 10);
        jLayeredPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setText("Si vous vous trouvez dans la zone de dessin(le grand cadre blanc) et que le curseur de la souris est en forme de main,");
        jLabel12.setBounds(10, 60, 670, 14);
        jLayeredPane2.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setText("Vous n'avez plus qu'à cliquez à l'endroit de votre choix pour déposer un sommet, sinon, allez tout d'abord sélectionnez");
        jLabel13.setBounds(10, 70, 670, 20);
        jLayeredPane2.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setText("\" l'outils sommet \" dans la palette d'outils (à votre gauche),assurez vous que l'outils sélectionnez prend la couleur jaune");
        jLabel14.setBounds(10, 86, 670, 14);
        jLayeredPane2.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setText("et que le curseur de la souris prenne la forme d'une main. la couleur de dessin initiale d'un sommet est bleu-marine...");
        jLabel15.setBounds(10, 100, 670, 10);
        jLayeredPane2.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("1 - Ajout d'un sommet");
        jLabel16.setBounds(10, 30, 120, 14);
        jLayeredPane2.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setText("Tout comme l'ajout d'un sommet, l'ajout d'un arc est très simple. ");
        jLabel17.setBounds(10, 140, 670, 10);
        jLayeredPane2.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setText("Si vous vous trouvez dans la zone de dessin(le grand cadre blanc) et que le curseur de la souris est en forme de croix,");
        jLabel18.setBounds(10, 150, 670, 14);
        jLayeredPane2.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setText("cliquez dans le sommet de départ puis en vous déplaçant simplement avec le curseur de votre souris, allez cliquer dans");
        jLabel19.setBounds(10, 164, 670, 10);
        jLayeredPane2.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setText("le sommet d'arrivé, un arc est déssiné reliant les deux sommets, le sens de l'arc apparaîtra en fonction de la nature de");
        jLabel20.setBounds(10, 170, 670, 20);
        jLayeredPane2.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel21.setText("votre graphe. le coût de l'arc apparaît également.");
        jLabel21.setBounds(10, 180, 560, 20);
        jLayeredPane2.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel22.setText("Si le curseur de la souris n'est pas en forme de croix, sélectionnez l'outils Arête dans la palette d'outils.");
        jLabel22.setBounds(10, 200, 670, 14);
        jLayeredPane2.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel23.setText("Avant de tracer un Arc, rassurer vous toujours que le coût de l'arête afficher à gauche au dessus de la palette d'outils");
        jLabel23.setBounds(10, 210, 670, 14);
        jLayeredPane2.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel24.setText("correspond à votre valeur, sisnon, régler le à votre guise.");
        jLabel24.setBounds(10, 220, 670, 14);
        jLayeredPane2.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Etape 2", jLayeredPane2);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 255));
        jLabel25.setText("2 - Renommer un sommet");
        jLabel25.setBounds(370, 80, 310, 14);
        jLayeredPane3.add(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel26.setText("Pour afficher les détails d'un sommet, il y a rien de plus simple.");
        jLabel26.setBounds(10, 30, 670, 14);
        jLayeredPane3.add(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel27.setText("- Cliquez dans un sommet, rassurez-vous qu'un cercle de couleur rouge apparaît autour de ce dernier, ensuite cliquez");
        jLabel27.setBounds(10, 44, 670, 14);
        jLayeredPane3.add(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel28.setText("sur le boutton \" Details du sommet \" ou rendez-vous dans \" Graphe->Sommet->Détails \".");
        jLabel28.setBounds(10, 60, 670, 10);
        jLayeredPane3.add(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 255));
        jLabel29.setText("1 - Afficher les détails d'un sommet");
        jLabel29.setBounds(10, 10, 200, 14);
        jLayeredPane3.add(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphou/2013-05-01_083932.png"))); // NOI18N
        jButton3.setBounds(10, 80, 340, 190);
        jLayeredPane3.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel30.setText("- Cliquez sur le boutton \" Renommer \" ou  ");
        jLabel30.setBounds(370, 160, 310, 10);
        jLayeredPane3.add(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel31.setText("Pour renommer un sommet : ");
        jLabel31.setBounds(370, 100, 310, 14);
        jLayeredPane3.add(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel32.setText("- Cliquez dans le sommet.");
        jLabel32.setBounds(370, 120, 310, 14);
        jLayeredPane3.add(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel33.setText("- Rassurer-vous q'un cercle de couleur rouge");
        jLabel33.setBounds(370, 134, 310, 10);
        jLayeredPane3.add(jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel34.setText("apparaît autour de ce dernier.");
        jLabel34.setBounds(380, 140, 300, 20);
        jLayeredPane3.add(jLabel34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel35.setText("- rendez-vous  dans \" Graphe->Sommet->");
        jLabel35.setBounds(370, 170, 310, 14);
        jLayeredPane3.add(jLabel35, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel36.setText("Renommer\" .");
        jLabel36.setBounds(380, 180, 300, 20);
        jLayeredPane3.add(jLabel36, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Détails du Sommet", jLayeredPane3);

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 255));
        jLabel37.setText("1 - Exécution de l'agorithme de la recherche du plus court chemin");
        jLabel37.setBounds(10, 10, 350, 14);
        jLayeredPane4.add(jLabel37, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel38.setText("Une fois que vous avez fini de dessiner ou restaurer votre graphe, vous pouvez à tout moment lancer l'exécution de l'al ");
        jLabel38.setBounds(10, 30, 670, 14);
        jLayeredPane4.add(jLabel38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel39.setText("gorithme à condition que ce dernier respecte les conditions requises. le programme affiche le plus court chemin s'il existe");
        jLabel39.setBounds(10, 40, 670, 14);
        jLayeredPane4.add(jLabel39, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel40.setText("bien sûre entre le sommet de plus petit numéro et le sommet de plus grand numéro (chemin élémentaire) en coloriant");
        jLabel40.setBounds(10, 50, 670, 20);
        jLayeredPane4.add(jLabel40, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel41.setText("tous les arcs qui le constitue en couleur orange. la valeur de ce chemin est affiché à gauche en dessous de la palette ");
        jLabel41.setBounds(10, 64, 670, 20);
        jLayeredPane4.add(jLabel41, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel42.setText("- Lancez la recherche du plus court chemin entre X et Y en cliquant sur \"Ok\"");
        jLabel42.setBounds(210, 190, 470, 14);
        jLayeredPane4.add(jLabel42, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel43.setText("d'outils. Pour exécuter cet algorithme, il suffit de cliquez sur le boutton suivant : ");
        jLabel43.setBounds(10, 90, 440, 14);
        jLayeredPane4.add(jLabel43, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel44.setText("ou rendez-vous dans \" Graphe->Moore \".");
        jLabel44.setBounds(10, 100, 390, 20);
        jLayeredPane4.add(jLabel44, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel45.setText("Pour afficher le plus court chemin entre 2 sommets quelconques,");
        jLabel45.setBounds(10, 130, 550, 20);
        jLayeredPane4.add(jLabel45, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel46.setText("rendez - vous dans la zone suivante : ");
        jLabel46.setBounds(10, 140, 470, 20);
        jLayeredPane4.add(jLabel46, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel47.setText(" - Déroulez pour choisir le numéro du sommet de départ (X).");
        jLabel47.setBounds(210, 160, 450, 20);
        jLayeredPane4.add(jLabel47, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel48.setText(" - Déroulez pour choisir le numéro du sommet d'arrivé (Y).");
        jLabel48.setBounds(210, 174, 470, 20);
        jLayeredPane4.add(jLabel48, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphou/moore.png"))); // NOI18N
        jLabel51.setBounds(450, 80, 130, 30);
        jLayeredPane4.add(jLabel51, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphou/pal.png"))); // NOI18N
        jLabel52.setBounds(10, 160, 190, 90);
        jLayeredPane4.add(jLabel52, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Plus court chemin", jLayeredPane4);

        jLabel49.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 255));
        jLabel49.setText("1 - Exécution de l'agorithme du coloriage");
        jLabel49.setBounds(10, 10, 350, 14);
        jLayeredPane5.add(jLabel49, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphou/cap.png"))); // NOI18N
        jLabel50.setBounds(10, 30, 190, 210);
        jLayeredPane5.add(jLabel50, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphou/colo.png"))); // NOI18N
        jLabel53.setBounds(230, 170, 150, 30);
        jLayeredPane5.add(jLabel53, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel54.setText("Une fois que vous avez fini d'éditer ou de retaurer votre graphe, vous");
        jLabel54.setBounds(230, 40, 450, 14);
        jLayeredPane5.add(jLabel54, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel55.setText("pouvez à tout moment le colorier ou changer de couleur en cliquant sur ");
        jLabel55.setBounds(230, 50, 450, 20);
        jLayeredPane5.add(jLabel55, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel56.setText("le boutton colorier en bas (2ème boutton en dessous de la zone de dessin)");
        jLabel56.setBounds(230, 66, 450, 14);
        jLayeredPane5.add(jLabel56, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel57.setText("ou rendez - vous dans \" Graphe->Coloriage \"");
        jLabel57.setBounds(230, 80, 440, 14);
        jLayeredPane5.add(jLabel57, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel58.setText("Votre graphe sera alors colorier à condition qu'il respecte les exigences");
        jLabel58.setBounds(230, 100, 450, 14);
        jLayeredPane5.add(jLabel58, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel59.setText("requises.");
        jLabel59.setBounds(230, 110, 330, 20);
        jLayeredPane5.add(jLabel59, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphou/colo2.png"))); // NOI18N
        jLabel60.setBounds(400, 170, 150, 30);
        jLayeredPane5.add(jLabel60, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel5.setBounds(0, 0, 690, 300);
        jLayeredPane5.add(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Coloriage du graphe", jLayeredPane5);

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextPane1.setText("Graph'ou ouffre également la possibilité de réaliser baucoup d'autres choses entre autre la sauvegarde, la restauration des graphes (au format \" .kmk \"), grâce à l'onglet << Détails >> du menu graphe, il est possible de déterminer le nombre de chemin de longueur \" A \" entre deux sommets X et Y, à vous de preciser A,X et Y. il est également possible de connaître le nombre de circuit ou de chaîne de longueur X, bien sûre il vous revient de préciser la longueur de X;");
        jScrollPane1.setViewportView(jTextPane1);

        jScrollPane1.setBounds(70, 100, 540, 80);
        jLayeredPane6.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("Autres", jLayeredPane6);

        jLabel61.setText("Graph'ou est une application qui a été devéloppé dans le cadre d'un projet scolaire par un étudiant du niveau 3");
        jLabel61.setBounds(30, 30, 640, 14);
        jLayeredPane7.add(jLabel61, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel62.setText("vos remarques, vos critiques et vos suggestions, veuillez nous contacter aux adresses suivantes : ");
        jLabel62.setBounds(30, 70, 640, 14);
        jLayeredPane7.add(jLabel62, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel63.setText("en cycle d'ingénieur de travaux informatique option génie logiciel (année universiataire 2012/2013). pour toutes");
        jLabel63.setBounds(30, 50, 640, 14);
        jLayeredPane7.add(jLabel63, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel64.setText("e-mail : kibonguestephaneivalain@rocketmail.com");
        jLabel64.setBounds(30, 120, 290, 14);
        jLayeredPane7.add(jLabel64, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel65.setText("Téléphone : (+237) 98-28-40-00");
        jLabel65.setBounds(30, 100, 520, 14);
        jLayeredPane7.add(jLabel65, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphou/bluff.png"))); // NOI18N
        jLabel66.setBounds(350, 90, 320, 200);
        jLayeredPane7.add(jLabel66, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel7.setBounds(0, 0, 690, 300);
        jLayeredPane7.add(jPanel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("A propos", jLayeredPane7);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setText("Bienvenue dans l'aide pas à pas de GRAPH'OU");

        jButton1.setText("Ok");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addGap(0, 196, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Aide dialog = new Aide(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
