/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphou;

import java.util.Vector;

/**
 *
 * @author stephane
 */
public final class Distance extends javax.swing.JDialog {

    /**
     * Creates new form Distance
     */
    public Distance(java.awt.Frame parent, boolean modal,int [][] mat,Vector so) 
    {
        super(parent, modal);
        matrice = new int[mat.length][mat.length];
        sommet = new Vector();
        sommet = so;
        matrice = mat;
        initComponents();
        initialisation();
        String mati="-------------------------\n   Matrice initiale   \n-------------------------\n";
        for(int i=0;i<mat.length;i++){
            for(int j=0;j<mat.length;j++){
                mati+=(mat[i][j]>0?1:0)+" ";
            }
            mati +="\n"; 
        }
        matini.setText(mati);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        x = new javax.swing.JComboBox();
        y = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        lg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lg1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        matini = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        matfinal = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nombre de sommet de longuer \"a\" Du sommet \"x\" au sommet \"y\"");
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nombre de sommet de longueur \"a\"");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, 218, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Du sommet X au sommet Y");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 31, 160, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("X : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Y : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 70, -1, -1));

        x.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        getContentPane().add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 63, 89, 29));

        y.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        getContentPane().add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 63, 89, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Longueur des chemins : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 109, -1, -1));

        lg.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        getContentPane().add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 103, 89, 27));

        jButton1.setText("Ok");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 141, 89, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 171, 242, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Résultat"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        result.setEditable(false);
        result.setColumns(18);
        result.setRows(5);
        jScrollPane1.setViewportView(result);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 279, 250, 140));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Nombre de circuit de longueur X");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Valeur de X : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 223, -1, -1));

        lg1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        getContentPane().add(lg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 217, 88, 27));

        jButton2.setText("Ok");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 250, 88, -1));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        matini.setEditable(false);
        matini.setColumns(20);
        matini.setRows(5);
        jScrollPane2.setViewportView(matini);

        jSplitPane1.setTopComponent(jScrollPane2);

        matfinal.setEditable(false);
        matfinal.setColumns(20);
        matfinal.setRows(5);
        jScrollPane3.setViewportView(matfinal);

        jSplitPane1.setRightComponent(jScrollPane3);

        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 350, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean testchaine (String a,int mode) 
    {
        String chiffre="0123456789";
        
        if(a.isEmpty()) {
            return false;
        }
        switch(mode)
        {
            case 1:
            {
              for(int i=0;i<a.length();i++)
              {
                  if(chiffre.indexOf(a.charAt(i))<0) {
                      return false;
                  }
                  return true;
              }
            };break;
            default: return false; 
        }
        return false;
    }
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(!lg.getText().isEmpty())
        {
          String a = lg.getText();
          int i;
          if(testchaine(a,1))
          {
            i = Integer.parseInt(a);
            Pmatriciel kandor = new Pmatriciel(matrice, i,(int)x.getSelectedIndex(),(int)y.getSelectedIndex());
            result.setText("Le nombre de chemin de longueur : "+i+"\nEntre le sommet '"+x.getSelectedItem()
                    + "' \net le sommet '"+y.getSelectedItem()+"' est : "+kandor.nombre());
            matfinal.setText(kandor.exposant_str());
          }
          else
          {
              result.setText("Entrez une valeur entière. "+"\n"+a+" n'en n'est pas une");
          }
          
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       if(!lg1.getText().isEmpty())
        {
          String a;
            a = lg1.getText();
          int i;
          if(testchaine(a,1))
          {
            i = Integer.parseInt(a);
            Pmatriciel kandor = new Pmatriciel(matrice, i,(int)x.getSelectedIndex(),(int)y.getSelectedIndex());
            result.setText("Le nombre de circuit de longueur : "+i+"\nest : "+kandor.get_trace());
            matfinal.setText(kandor.exposant_str());
          }
          else
          {
              result.setText("Entrez une valeur entière. "+"\n"+a+" n'en n'est pas une");
          }
          
        }  
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public void initialisation()
    {
        for(int i=0;i<sommet.size();i++)
        {
            x.addItem(((Sommet)sommet.get(i)).get_nom());
            y.addItem(((Sommet)sommet.get(i)).get_nom());
        }
    }
     public void showDDialog()
     {
       this.setVisible(true);  
     }
    private int [][] matrice;
    private Vector sommet; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField lg;
    private javax.swing.JTextField lg1;
    private javax.swing.JTextArea matfinal;
    private javax.swing.JTextArea matini;
    private javax.swing.JTextArea result;
    private javax.swing.JComboBox x;
    private javax.swing.JComboBox y;
    // End of variables declaration//GEN-END:variables
}
