/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphou;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author stephane
 */
public class splashscreen extends javax.swing.JDialog {
    Timer time;
    int val;
    splashscreen mon_instance = this;
    
    /**
     * Creates new form splashscreen
     */
    public splashscreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        val = 0;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PG = new javax.swing.JProgressBar();
        tet = new javax.swing.JLabel();
        tet1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setIconImage(null);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphou/fond.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 110));

        PG.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        PG.setForeground(new java.awt.Color(51, 102, 255));
        PG.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(PG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 340, 10));

        tet.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        tet.setText("jLabel6");
        getContentPane().add(tet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        tet1.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        tet1.setForeground(new java.awt.Color(51, 102, 255));
        tet1.setText("Copyright (C) 2013, All rights reserved");
        getContentPane().add(tet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        PG.setMinimum(0);
        PG.setMaximum(75);
        PG.setStringPainted (true);
        val = 0;
        time=new Timer(175,new ActionListener() {
            
            

            @Override
            public void actionPerformed(ActionEvent ae) {
               
               if(val<75){
                   if(val > 1 && val <20){
                       tet.setText("Initialisation des interfaces...");
                   }
                   if(val>20 && val<40){
                       tet.setText("Initialisation des outils...");
                   }
                   if(val>40 && val<60){
                       tet.setText("Initialisation des algorithmes...");
                   }
                   if(val>60 && val<75){
                       tet.setText("Initialisation des R/S...");
                   }
                   val++;
                   PG.setValue(val);
               }
               else{
                        time.stop();
                        PG.setValue(75);
                        try{
                        for(int i=0;i<0b1001;i++){
                            mon_instance.setOpacity((float)(mon_instance.getOpacity() - 0.1f));
                            try {
	                          Thread.sleep(100);
	                    }
	                    catch ( InterruptedException e ) {
	                    }
                        }
	                    }
	                    catch ( Exception e ) {
	                    }
                        mon_instance.dispose();
               } 
               
            }
        });
        time.start();
    }//GEN-LAST:event_formWindowActivated

     public void ShowDialog()
     {
       this.setVisible(true);  
     }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar PG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tet;
    private javax.swing.JLabel tet1;
    // End of variables declaration//GEN-END:variables
}
